crate/cratedb-guide

docs/handbook/performance/inserts/methods.rst, docs/handbook/performance/inserts/tuning.rst
- Guide the user about running `ANALYZE` statements after large inserts.
- Add a hint about overload protection on `INSERT INTO` and `COPY FROM` statements.
Coming from https://github.com/crate/crate-howtos/pull/325. Thanks, @ckurze.
=> Performance: Add hints to overload protection and `ANALYZE` command

README.rst, docs/index.md
=> Chore: Renamed repository to `cratedb-guide` (singular)

docs/conf.py
It looks like Stackoverflow does not like to be requested from GitHub today. On the other hand, the link checker works well on my machine. It will probably need an adjustment on the "link ignore" settings, at least temporarily.
```
(admin/performance/selects: line   98) broken    https://stackoverflow.com/a/2705123 - 403 Client Error: Forbidden for url: https://stackoverflow.com/a/2705123
```
-- https://github.com/crate/cratedb-guide/actions/runs/7972899296/job/21765730000?pr=15#step:4:1004
=> Chore: Make link checker ignore links to Stack Overflow

docs/install/index.rst
The "install" page did not display well on smaller screens, like mobile phones.
Use responsive features of [Bootstrap](https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)) per [sphinx{design}](https://sphinx-design.readthedocs.io/).
Before: https://cratedb.com/docs/guide/install/index.html
After: https://cratedb-guide--32.org.readthedocs.build/install/index.html
/cc @karynzv, @seut, @matriv, @hlcianfagna, @hammerhead, @proddata, @ckurze
=> Style: Make tile gallery on "install" page responsive

docs/conf.py, docs/requirements.txt
Belongs to GH-11, but needs a new release of crate-docs-theme. cratedb-guide currently uses a pre-release `crate-docs-theme==0.30.0.dev3`, which includes this slot. GA releases don't, that's why the new thing is only semi-live.
Unless updating that upstream patch, this one will fail CI.
- https://github.com/crate/crate-docs-theme/pull/448
https://cratedb-guide--12.org.readthedocs.build/
=> Update to crate-docs-theme==0.30.0.dev5. Rename module slot to singular.

docs/admin/clustering/index.rst, docs/admin/index.rst, docs/admin/performance/index.rst, docs/domain/timeseries/index.rst, docs/install/debian-ubuntu.rst, docs/install/index.rst, docs/install/redhat.rst, docs/install/windows.rst
Starting each page with the venerable "This section of the documentation {covers,outlines,demonstrates}" is just too much boilerplate, no?
There are just four leftovers, which is acceptable.
=> Chore: Remove prose boilerplate "This section of the documentation"

docs/index.md
- Reorder sections on index.md to have more importance on the application domains and integrations over reference architectures.
=> Change section order on index page

docs/admin/index.rst, docs/admin/upgrade/full.rst, docs/admin/upgrade/index.md, docs/admin/upgrade/planning.rst, docs/admin/upgrade/rolling.rst
Spend a little index page on the "Upgrading" section, in order to save vertical space within the primary navigation, and to improve guidance.
With screenshots.
- https://cratedb-guide--43.org.readthedocs.build/admin/upgrade/
/cc @surister, @karynzv, @marijaselakovic, @hammerhead, @proddata, @wierdvanderhaar, @msbt, @matkuliak
=> Administration/Upgrading: Add index page for "Upgrading" section

docs/performance/selects.rst
Add two more references to tutorials on the community forum. Thanks, @hlcianfagna and @hammerhead.
- Performance: Add link to "Resampling time-series data with DATE_BIN"
- Performance: Add link to "Advanced downsampling with the LTTB algorithm"
- https://cratedb-guide--45.org.readthedocs.build/performance/selects.html#downsampling-with-date-bin
- https://cratedb-guide--45.org.readthedocs.build/performance/selects.html#downsampling-with-lttb
/cc @surister, @karynzv, @marijaselakovic, @seut, @wierdvanderhaar
=> Performance: Add links to downsampling tutorials

docs/admin/clustering/index.rst, docs/admin/clustering/scale-up-down.md
The dedicated "Expand Cluster" page now cross links to two community forum articles by @hlcianfagna. Thank you again. 🌻 
- [How to add new nodes to an existing cluster](https://community.cratedb.com/t/how-to-add-new-nodes-to-an-existing-cluster/1546)
- [Scaling CrateDB clusters up and down to cope with peaks in demand](https://community.cratedb.com/t/scaling-cratedb-clusters-up-and-down-to-cope-with-peaks-in-demand/1314)
https://cratedb-guide--46.org.readthedocs.build/admin/clustering/scale-up-down.html
/cc @karynzv, @marijaselakovic, @seut, @surister, @wierdvanderhaar, @matkuliak, @msbt
=> Administration/Clustering: Reference articles about scaling clusters

docs/requirements.txt
Make cratedb-guide always use the most recent release of crate-docs-theme, detouring from using a pre-release version.
/cc @seut, @ckurze
=> Update to vanilla / most recent crate-docs-theme

docs/conf.py, docs/install/configure.rst, docs/install/debian-ubuntu.rst, docs/install/redhat.rst
The new documentation section raised many 404 errors on the link checker service, because Sphinx generated the wrong links, considering the project to be versioned, like the others, while it isn't. This patch aims to remedy them.
Screenshots about two occasions where the wrong links have been used.
https://cratedb-guide--61.org.readthedocs.build/
=> Sphinx settings: Configure that project is not using versioning or i18n

docs/index.md
The grid isn't responsive, following [this guide](https://mystmd.org/guide/dropdowns-cards-and-tabs#grids), this should make it 1 col on extra-small devices (<576px), 2 col on small (768px) and 3 col on medium (992px) and large screens (>1200px) - not the first element though, this will stay 2 col.
=> Improve grid display on mobile

docs/domain/ml/tensorflow.rst, docs/index.md
Fixes a wrongly assigned link on the main intro page. Thanks for reporting, @hlcianfagna.
=> Chore: Fix link to "Data Visualization" page

docs/build.json, docs/conf.py, docs/domain/timeseries/generate/cli.rst, docs/install/_post-install.rst
- Fixed outdated references
- Bumped `build.json` version to 2.1.2
=> Fix references to outdated projects

docs/install/redhat.rst
Registering with the RPM package repository using the `crate-release-7.0-1.x86_64.rpm` packages and friends is being deprecated. It is advised to configure the RPM repository manually instead.
https://cratedb-guide--69.org.readthedocs.build/install/redhat.html
I've only edited the documentation, **without doing any kind of validation yet.** Maybe you can spare a few minutes? Thanks for your support!
/cc @hlcianfagna, @WalBeh, @BaurzhanSakhariev, @matriv
=> Installation: Update section about installing RPM packages

docs/conf.py
Most recent `crate-docs-theme` removes the `canonical_url_path` theme option.
- Carry over a fix from preview PR GH-73.
=> Theme: Remove `canonical_url_path` theme option

docs/integrate/bi/powerbi-desktop.rst, docs/integrate/etl/index.md, docs/integrate/etl/influxdb.md
Main documentation for CrateDB Toolkit's InfluxDB I/O subsystem, based on influxio.
- [Import data from InfluxDB](https://cratedb-guide--75.org.readthedocs.build/integrate/etl/influxdb.html)
- https://github.com/crate/tech-content/issues/99
=> Document InfluxDB I/O procedures

docs/getting-started.md
Fixes a small typo in the Getting Started guide.
Fixes a small typo in the text.
=> Fixed small typo in Getting Started Guide.

docs/integrate/etl/index.md
Add links to tutorials about integrating CrateDB with [Apache Hop](https://hop.apache.org/) and [Apache NiFi](https://nifi.apache.org/). Thanks, @hlcianfagna and @hammerhead.
- https://cratedb-guide--83.org.readthedocs.build/integrate/etl/index.html#apache-hop
- https://cratedb-guide--83.org.readthedocs.build/integrate/etl/index.html#apache-nifi
- https://github.com/crate/crate-clients-tools/pull/64
- https://github.com/crate/crate-clients-tools/pull/125
=> ETL: Add Apache Hop and Apache NiFi

docs/integrate/etl/influxdb.md
Original tutorial only contained instructions for local instances of both DBs, this PR adds cloud-to-cloud variant.
https://cratedb-guide--88.org.readthedocs.build/integrate/etl/influxdb.html#cloud-migration
=> ETL: Add cloud-to-cloud instructions to InfluxDB I/O tutorial

docs/integrate/etl/influxdb.md
A few improvements to the InfluxDB import tutorial.
- Add admonition about beta status
- Add section about InfluxDB jargon
- Improve wording
- https://cratedb-guide--89.org.readthedocs.build/integrate/etl/influxdb.html
=> ETL: Improve tutorial about InfluxDB

docs/integrate/etl/influxdb.md
=> Fixing punctuation and adding a URL to the Influx adapter repo

docs/integrate/etl/index.md
Let's fix this in the most straightforward way.
---
kudos to @amotl for finding this
> [!note]
> _"So let's find the closest header in the document and try with that one."_
> https://github.com/petermd/sphinx_rtd_theme/blob/0.2.4/js/theme.js#L93-L123
:tv: [Preview](https://cratedb-guide--91.org.readthedocs.build/)
⬆️ ⬆️ ⬆️
=> fix highlighting for etl pages

docs/domain/timeseries/normalize-intervals.rst, docs/install/cloud/aws/aws-terraform-setup.rst, docs/install/windows.rst, docs/integrate/orm.md
When rebuilding this project on RTD, there have been link checker errors.
=> Chore: Fix broken links

docs/home/index.md, docs/requirements.txt
There was a proposal to have a dedicated landing page for the documentation section at https://cratedb.com/docs/, which should refer to the most relevant 1st-level pillars of our documentation tree.
**Preview:** [Docs Home](https://cratedb-guide--94.org.readthedocs.build/home/)
This page is special, should not necessarily be part of the content tree, that's why it is flagged as **orphaned**, concerning Sphinx technicalities.
The aim is to slot this page into the URL namespace as a landing page for all the documentation based on Sphinx, straight at https://cratedb.com/docs/, by using corresponding Nginx configuration snippets.
- https://github.com/crate/tech-content/issues/105
This is just a quick proposal, which most definitively has flaws on different details. It intends to give you a …
=> Home: Add new top-level documentation landing page, indexing the main entrypoints

docs/admin/troubleshooting/jcmd/docker.rst
The procedure to use jcmd to attach to the CrateDB process running inside a container, by needing to prefix a `chroot` command, is apparently no longer needed.
chroot --userspec=1000 /
Instead, it is sufficient to use `--user=crate` on the `docker run` command today, apparently.
docker exec -it --user=crate cratedb /bin/bash
/crate/jdk/bin/jcmd 1 VM.version
=> Troubleshooting: Trim page about "Using `jcmd` with CrateDB on Docker"

docs/domain/ml/index.md, docs/install/cloud/aws/aws-terraform-setup.rst
- Make CI pass on GH-99.
Apparently, a newer release of docutils is more strict, and bails out when reading invalid markup.
```
WARNING: 'grid-item': Splitting content across first line and body,
when an options block is present, is not recommended [myst.directive_parse]
```
=> Fix docutils warnings for updating to new crate-docs-theme

docs/conf.py, docs/feature/index/index.md, docs/feature/query/index.md, docs/index.md, docs/migrate/index.md, docs/migrate/rockset/index.md, docs/migrate/rockset/query.md, docs/requirements.txt
In the course of the Rockset HTTP API going out of service, others are ramping up their offerings. This page intends to summarize relevant topics from a more technical / developer documentation perspective, this time focused on CrateDB.
The page is also suitable to help people just learning CrateDB to quickly gain a few concise insights without much ado. /cc @kneth
- [Welcome Rockset Developers](https://cratedb-guide--98.org.readthedocs.build/migrate/rockset/)
- ~~**Currently, this is a very early preview.** The page certainly needs more attention and sanding, based on your feedback and efforts. Thanks!~~
- **~~Second~~ Third iteration completed.** Suggestions on improving the wording and beyond are much welcome. /cc @surister, @hammerhead, @hlcianfagna, @ckurze, @geragray, @simonprickett …
=> Migration: Add page about Rockset

docs/migrate/rockset/index.md
Coming from GH-98, this patch updates the documentation page about migrations from Rockset.
https://cratedb-guide--107.org.readthedocs.build/migrate/rockset/
- Discriminate between previous and next webinar on the right hand side in the header section.
- Update appointment time for next webinar.
- Add information about integration PoCs with CrateDB-native DynamoDB CDC and MongoDB CDC in the footer section, also referring to 3rd party applications like Debezium or StreamSets.
/cc @ckurze, @geragray
=> Migration/Rockset: Updates about previous/next webinar, and integrations

docs/_include/links.md, docs/feature/relational/index.md, docs/integrate/cdc/index.md, docs/integrate/etl/index.md, docs/integrate/etl/streamsets.rst, docs/integrate/index.md, docs/migrate/rockset/index.md
Building upon GH-107, and including a few other resources, this patch adds a dedicated page about Change Data Capture (CDC) to the documentation.
https://cratedb-guide--108.org.readthedocs.build/integrate/cdc/
- Absorb Debezium item from the ETL section
- Add item about CrateDB-native DynamoDB CDC
- Add item about CrateDB-native MongoDB CDC
- Reference item about StreamSets Data Collector in the ETL section
/cc @ckurze, @geragray
=> Integration/CDC: Add dedicated page about CDC matters

docs/install/tarball.rst
Clarify that on macOS permissions need to be added when running a specific version from tarball for the first time 
https://cratedb-guide--111.org.readthedocs.build/install/tarball.html#install-macos
=> Install: Clarify tarball installation on macOS

docs/_include/links.md, docs/integrate/cdc/index.md, docs/integrate/etl/index.md
A broken Markdown/MyST link.
> ![image](https://github.com/user-attachments/assets/cf8af085-41f0-4e56-8fc5-a3fd8d5d4367)
>
> -- https://cratedb.com/docs/guide/integrate/etl/index.html#apache-kafka
Why doesn't the link checker probe them correctly? Most probably, MyST would be responsible in one way or another?
=> Chore: Fix broken Markdown link on integrate/etl/index

docs/install/container/kubernetes/kubernetes-operator.rst
Nodes data name needs to be "hot" for `change_compute` to work to align with https://github.com/crate/crate-operator/blob/20468eb6b70e16f901e6e7551e1de5c568ede88c/crate/operator/main.py#L349
=> Amend example to work with change_compute operations

docs/install/cloud/aws/ec2-setup.rst
```
(install/cloud/aws/ec2-setup: line  112) broken    https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#launch-instance-with-role-cli - Anchor 'launch-instance-with-role-cli' not found
(install/cloud/aws/ec2-setup: line  112) broken    https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#launch-instance-with-role-console - Anchor 'launch-instance-with-role-console' not found
```
=> Fix broken links in EC2 page

docs/_include/links.md, docs/conf.py, docs/domain/ml/index.md, docs/feature/search/vector/index.md, docs/integrate/cdc/index.md, docs/integrate/etl/index.md, docs/migrate/rockset/index.md
Coming from recent improvements to the `ctk load table` I/O subsystem, this patch brings the documentation up to speed.
- https://cratedb-guide--122.org.readthedocs.build/integrate/etl/
- https://cratedb-guide--122.org.readthedocs.build/integrate/cdc/
- https://cratedb-guide--122.org.readthedocs.build/migrate/rockset/
=> ETL/CDC: Updates about DynamoDB, Kinesis, MongoDB, and Rockset

docs/_include/links.md, docs/integrate/cdc/index.md, docs/integrate/etl/index.md, docs/migrate/rockset/index.md
The documentation did not include any pointers to AWS DMS yet.
- https://cratedb-guide--123.org.readthedocs.build/integrate/etl/#aws-dms
- https://cratedb-guide--123.org.readthedocs.build/integrate/cdc/#aws-dms
- https://cratedb-guide--123.org.readthedocs.build/migrate/rockset/#integrate
=> ETL/CDC: Add information about AWS Database Migration Service (AWS DMS)

docs/integrate/testing.md
pytest-cratedb has been modernized recently, and already works well on a few projects. Let's also advertise it here.
https://cratedb-guide--128.org.readthedocs.build/integrate/testing.html#python-pytest
=> Chore: Update designated pytest package to be `pytest-cratedb`

docs/domain/index.md, docs/domain/ml/index.md
@simonprickett recently contributed an example program [^1] that uses [LlamaIndex](https://www.llamaindex.ai/framework), extracted and re-assembled from a tutorial [^2] that has been modernized. Thanks!
[^1]: https://github.com/crate/cratedb-examples/tree/main/topic/machine-learning/llama-index
[^2]: https://community.cratedb.com/t/how-to-connect-your-cratedb-data-to-llm-with-llamaindex-and-azure-openai/1612
https://cratedb-guide--132.org.readthedocs.build/domain/ml/index.html#llamaindex
Please suggest any improvements on wording and beyond which come to mind. Thanks!
/cc @surister
=> ML/LlamaIndex: Add section about example program accompanying tutorial

docs/feature/search/geo/index.md
Apply some cleanups to the [Geospatial Search](https://cratedb.com/docs/guide/feature/search/geo/) page, and add the video about [Plane Spotting with CrateDB](https://www.youtube.com/watch?v=YIUJTbrwlAs).
https://cratedb-guide--134.org.readthedocs.build/feature/search/geo/index.html#learn
Please suggest wording improvements and anything else which comes to mind for improving this canonical feature page. Thanks!
/cc @surister, @kneth
=> Feature/Geo: Cleanups. Add "Plane Spotting with CrateDB" video.

docs/feature/connectivity/index.md
The [Feature » Connectivity](https://cratedb.com/docs/guide/feature/connectivity/) page wasn't in a good shape yet. @kneth discovered that recently.
This patch intends to converge the page into the same layout/shape/style like all the others in the "All Features" section, using the same compact backbone made of "Intro", "Synopsis", and "Learn" subsections.
https://cratedb-guide--135.org.readthedocs.build/feature/connectivity/
- _Please visit inline comments._
- We believe the "tabs" approach will not scale, so we diverted using the "dropdowns" approach, currently showing both variants. Please advise.
This refactors a bit of content from a few sibling pages in crate-clients-tools. [^1]
- https://github.com/crate/crate-clients-tools/tree/main/docs/connect
- …
=> Feature/Connectivity: Rework page

docs/_include/card/timeseries-dask.md, docs/_include/card/timeseries-intro.md, docs/_include/links.md, docs/domain/timeseries/fundamentals.md, docs/domain/timeseries/index.md, docs/domain/timeseries/learn/query.md
The [Time Series Fundamentals with CrateDB](https://cratedb.com/docs/guide/domain/timeseries/fundamentals.html) page was very sloppily cobbled together the other day.
This patch intends to provide more structure and tangibility.
Added references to the CrateDB Academy, a relevant White Paper, and the corresponding product page on the website.
- https://cratedb-guide--133.org.readthedocs.build/domain/timeseries/
- https://cratedb-guide--133.org.readthedocs.build/domain/timeseries/fundamentals.html
Please provide advises in wording and layout, and overall ideas how to improve information conveyance on this topic, either within this PR, or separately, when applicable.
/cc @surister, @ckurze, @geragray
=> Domain/Time Series: Improve "Time Series Fundamentals with CrateDB" page

docs/home/index.md
@kneth signalled interest to increase awareness about the [All Features](https://cratedb.com/docs/guide/feature/) page.
This patch intends to add a reference to the [Docs Home](https://cratedb.com/docs/guide/home/) page.
https://cratedb-guide--131.org.readthedocs.build/home/
Please suggest any kinds of improvements, in wording, layout, and style. If you have suggestions to use different icons, please head over to [Material Symbols and Icons](https://fonts.google.com/icons).
/cc @surister, @simonprickett, @proddata, @geragray 
- https://github.com/crate/crate-docs-theme/pull/547
=> Home: Add card with reference to "All Features" page

docs/home/index.md
That's a little update to fix the improvement to the canonical landing page contributed by @geragray, so that it can be merged without much ado. The original patch failed to pass CI, because some card elements used the wrong symbols, nothing wild.
- GH-139
https://cratedb-guide--140.org.readthedocs.build/home/
I've deliberately added a button-style element to turn the plain link into an emphasized "call for action". Let us know if it's not applicable.
=> Home: Fix syntax on landing page update

docs/feature/search/vector/index.md
We found the [canonical feature page about vector search](https://cratedb.com/docs/guide/feature/search/vector/) lacked a reference to the [VECTOR_SIMILARITY](https://cratedb.com/docs/crate/reference/en/latest/general/builtins/scalar-functions.html#scalar-vector-similarity) SQL function, that was added on a later iteration, after initially conceiving that page.
https://cratedb-guide--144.org.readthedocs.build/feature/search/vector/
If you have any other material in this regard we could bring into this page, please let us know.
/cc @karynzv, @wierdvanderhaar, @hlcianfagna, @hammerhead
=> Feature/Search/Vector: Educate about `VECTOR_SIMILARITY` function

docs/domain/ml/index.md, docs/integrate/apache-flink/index.md, docs/integrate/apache-superset/index.md, docs/integrate/bi/index.md, docs/integrate/cdc/index.md, docs/integrate/dbt/index.md, docs/integrate/etl/index.md, docs/integrate/langchain/index.md, docs/integrate/llamaindex/index.md, docs/integrate/visualize/index.md
Introduce canonical pages for integrations with CrateDB, by pulling in content from the [Ecosystem Catalog](https://cratedb.com/docs/crate/clients-tools/), and extending it with educational resources (tutorials, webinars, hands-on instructions, and code / configuration snippets).
- [Apache Flink](https://cratedb-guide--145.org.readthedocs.build/integrate/apache-flink/)
- [Apache Superset](https://cratedb-guide--145.org.readthedocs.build/integrate/apache-superset/)
- [dbt](https://cratedb-guide--145.org.readthedocs.build/integrate/dbt/)
- [LangChain](https://cratedb-guide--145.org.readthedocs.build/integrate/langchain/)
- [LlamaIndex](https://cratedb-guide--145.org.readthedocs.build/integrate/llamaindex/)
- https://github.com/crate/crate-clients-tools/pull/154
=> Integrations: Consolidate section ingredients into flat list, and expand in-depth, part 1

docs/admin/memory.rst
Add warning about the advice to configure heap dump. 
Basically:
heap dump is workload dependent
must test
may crash otherwise
=> Memory Configuration: Add warnings about configuring heap size

docs/admin/clustering/index.rst, docs/admin/clustering/scale/auto.md, docs/admin/clustering/scale/demand.md, docs/admin/clustering/scale/expand.md, docs/admin/clustering/scale/index.md, docs/admin/clustering/scale/kubernetes.rst
Rework the whole section about scaling CrateDB Clusters. Feedback is very much welcome.
**Current:** https://cratedb.com/docs/guide/admin/clustering/scale-up-down.html
**Next:** https://cratedb-guide--150.org.readthedocs.build/admin/clustering/scale/
The patch absorbs those tutorials previously published on the community forum. Thanks for your excellent work. 💯 [^1]
- https://community.cratedb.com/t/how-to-add-new-nodes-to-an-existing-cluster/1546
- https://community.cratedb.com/t/scaling-cratedb-clusters-up-and-down-to-cope-with-peaks-in-demand/1314
- https://community.cratedb.com/t/autoscale-a-cratedb-cloud-cluster/1731
- https://github.com/crate/cratedb-guide/issues/148
- https://github.com/crate/infrastructure/pull/3248
[^1]: I will add a bit of polishing to them on behalf of a …
=> Scale: Refurbish section, and absorb relevant tutorials from community forum

docs/admin/clustering/scale/auto.md, docs/admin/clustering/scale/demand.md
On recently migrated articles, the images on Discourse are gone now.
=> Scale: Fix image URLs s/Discourse/GitHub/

docs/_include/links.md, docs/integrate/datagrip/index.md, docs/integrate/ide.md, docs/integrate/index.md, docs/migrate/rockset/index.md
Refactor an item from the [Ecosystem Catalog](https://cratedb.com/docs/clients/) into a dedicated page in the [CrateDB Guide](https://cratedb.com/docs/guide/).
https://cratedb-guide--155.org.readthedocs.build/integrate/datagrip/
- GH-157
- https://github.com/crate/crate-clients-tools/pull/157
=> Integrate: Add dedicated page about DataGrip

docs/conf.py, docs/integrate/dbt/index.md
At https://github.com/dbt-labs/docs.getdbt.com/pull/6564#pullrequestreview-2492313941, @amychen1776 said:
> as a heads up for your own documentation - we no longer called dbt data build tool. It's just dbt and is no longer broken out
This patch intends to fix the wording. Thanks, Amy.
=> dbt: Improve wording

docs/conf.py
Link checker was failing here. Some rendering on PyPI might have changed?
```
(integrate/testing: line   27) broken    https://pypi.org/project/cr8/#run-crate - Anchor 'run-crate' not found
```
-- https://github.com/crate/cratedb-guide/actions/runs/12273753962/job/34255514597?pr=154#step:4:1605
=> Chore: Fix link checker re. anchor not found on pypi.org

docs/integrate/langchain/index.md
After quite a bit of back and forth, and a slow genesis in general, this subsystem is finally approaching departures to take off.
https://cratedb-guide--166.org.readthedocs.build/integrate/langchain/
- https://github.com/crate/cratedb-examples/pull/773
=> LangChain: Update to langchain-cratedb 0.0.0

docs/domain/timeseries/longterm.md
This addresses
```
(domain/timeseries/longterm: line   93) broken    https://wetterdienst.readthedocs.io/en/latest/usage/python-api.html#export - 404 Client Error: Not Found for url: https://wetterdienst.readthedocs.io/en/latest/usage/python-api.html
```
=> Fix broken link to Wetterdienst docs

docs/_include/links.md, docs/integrate/datagrip/index.md, docs/integrate/dbeaver/index.md, docs/integrate/ide.md
Refactor an item from the [Ecosystem Catalog](https://cratedb.com/docs/clients/) into a dedicated page in the [CrateDB Guide](https://cratedb.com/docs/guide/).
https://cratedb-guide--157.org.readthedocs.build/integrate/dbeaver/
- GH-155
- https://github.com/crate/crate-clients-tools/pull/157
=> Integrate: Add dedicated page about DBeaver

docs/migrate/rockset/query.md
This add the equivalence for `REGEXP_LIKE` to the page which covers the translation of queries from Rockset
Ref https://docs.rockset.com/documentation/reference/regular-expression-functions
=> Add REGEXP_LIKE to list of Rockset function equivalences

docs/domain/timeseries/generate/node.rst, docs/integrate/dbt/index.md, docs/integrate/dbt/usage.md
Refurbish layout of dbt page, and absorb content from community tutorial "[Using dbt with CrateDB](https://community.cratedb.com/t/using-dbt-with-cratedb/1566)" by @hlcianfagna. Thanks and cheers!
https://cratedb-guide--153.org.readthedocs.build/integrate/dbt/
https://cratedb-guide--153.org.readthedocs.build/integrate/dbt/usage.html
=> dbt: Improve entry point page. Absorb community tutorial.

docs/integrate/langchain/index.md
It has been pointing to the workbench repository.
=> LangChain: Update link to adapter package

docs/feature/document/learn.md
I've updated the URL used to access the example data to be the CrateDB one rather than direct access from GitHub.
=> Updated URL used to access example data.

docs/domain/timeseries/learn/query.md
Updated the `COPY FROM` URL to be the Crate CDN one.
=> Updated COPY FROM URL for timeseries example.

docs/domain/timeseries/learn/with-metadata.md
Fixed the dataset URLs on the metadata page to be the new location.
=> Fixed dataset URLs on the metadata page.

docs/feature/search/fts/learn.md
Fixed the dataset URL in the fulltext example to be at the new location.
=> Fixed dataset URL in fulltext example to be at the new location.

docs/integrate/testing.md, docs/integrate/visualize/r.rst
The canonical documentation page has been erected in a haste, focused on Python and Testcontainers/Java, so it was natural it forgot to educate about the `io.crate:crate-testing` package.
- https://github.com/crate/crate-java-testing
- https://repo1.maven.org/maven2/io/crate/crate-testing/
https://cratedb-guide--178.org.readthedocs.build/integrate/testing.html
/cc @seut
=> Testing/Java: Add section about `io.crate:crate-testing` package

docs/install/index.rst
=> Fix link to tarball installation

docs/conf.py
Building `cratedb-guide` still failed the link checker on www.gnu.org being protected by a WAF configuration these days, because relevant link checker ignores have not been inherited from the parent theme.
- GH-189
=> Fix link checker by inheriting settings from parent theme

docs/performance/index.rst, docs/performance/scaling.rst
Just a minor adjustment about page names and link anchor labels.
=> Naming things: Use "Optimization and scaling", not "productizing"

docs/feature/cloud/index.md, docs/integrate/visualize/metabase.rst
What the title says.
- https://github.com/crate/cloud-docs/pull/97
=> Fix broken links: Documentation about CrateDB Edge has been removed

.github/workflows/docs.yml
The CI workflows' intentions here are mostly to run the link checker, so it's not too much connected to covering operating systems.
By removing the checks for macOS, the process will relax pressure on downstream resources, aiming for making it more unlikely to hit rate limiting measures.
It's not just rate limiting, it's also **429 Too Many Requests**.
```
(integrate/langchain/index: line  141) broken    https://github.com/crate/cratedb-examples/blob/main/topic/machine-learning/llm-langchain/conversational_memory.ipynb -
429 Client Error: Too Many Requests for url: https://github.com/crate/cratedb-examples/blob/main/topic/machine-learning/llm-langchain/conversational_memory.ipynb
```
-- https://github.com/crate/cratedb-guide/actions/runs/14926973334/job/41933954698?pr=199#step:4:1689
- …
=> CI: Remove building docs on macOS

docs/home/index.md
The "Resources" contained links to information that was already part of the page. So I removed those duplicate links away for simplicity. So now it's focused on "additional" resources not mentioned on the page already.
UPDATE:
I ended up removing them entirely as they are all both present in the left navbar or the top menu bar and in addition mentioned inside the page.
=> Remove duplicate resource links in index.md

docs/performance/inserts/sequences.rst, docs/performance/inserts/testing.rst
Snippet is broken because its using spaces
=> Fix bad indentation in code snippet

docs/integrate/index.md, docs/integrate/mcp/community.md, docs/integrate/mcp/cratedb-mcp.md, docs/integrate/mcp/index.md
Let's refer to existing resources about CrateDB and MCP.
- https://pypi.org/project/cratedb-mcp/
- https://cratedb-toolkit.readthedocs.io/query/mcp/
- https://github.com/crate/cratedb-examples/tree/main/framework/mcp
- https://cratedb-guide--204.org.readthedocs.build/integrate/mcp/
- Depends on: https://github.com/crate/cratedb-mcp/pull/23
/cc @hlcianfagna, @hammerhead, @WalBeh
=> MCP: Add first wave of material, mostly indexing existing others

docs/integrate/etl/index.md, docs/integrate/risingwave/index.md
Add a product card page for RisingWave, to be accompanied by relevant tutorials.
https://cratedb-guide--210.org.readthedocs.build/integrate/risingwave/
- https://github.com/crate/crate-clients-tools/discussions/263
- https://github.com/crate/cratedb-guide/pull/207#discussion_r2128676640
<details><summary>Details</summary>
<p>
</p>
</details>
=> RisingWave: Add index page

docs/integrate/estuary/index.md, docs/integrate/etl/index.md
Add a product card page for Estuary, possibly to be accompanied by relevant tutorials.
https://cratedb-guide--211.org.readthedocs.build/integrate/estuary/
=> Estuary: Add index page

docs/integrate/etl/iceberg-risingwave.md, docs/integrate/etl/index.md, docs/integrate/risingwave/index.md
An example with data coming from an Apache Iceberg table and aggregations materialized in real-time in CrateDB, using RisingWave. [RisingWave](https://github.com/risingwavelabs/risingwave) is a stream processing platform that allows configuring data sources, views on that data, and destinations where results are materialized.
https://cratedb-guide--207.org.readthedocs.build/integrate/etl/iceberg-risingwave.html
- https://github.com/crate/crate-clients-tools/discussions/263
- https://github.com/crate/crate-clients-tools/discussions/215
- https://github.com/crate/cratedb-toolkit/pull/444
=> RisingWave: Tutorial about Apache Iceberg -> CrateDB

docs/_include/links.md, docs/domain/ml/index.md, docs/domain/timeseries/advanced.md, docs/integrate/langchain/index.md, docs/integrate/llamaindex/index.md
What the title says. NB: Without a link checker, it wouldn't be possible to reorganize any content. Without a corresponding [job on CI](https://github.com/crate/cratedb-guide/actions/runs/16716394778), nobody would notice.
=> Fix broken links after reorg in `cratedb-examples`

docs/performance/storage.md
Update the page about "Performance » Storage Usage" regarding storage space improvements with CrateDB 5.10.
https://cratedb-guide--214.org.readthedocs.build/performance/storage.html
=> Storage Usage: Add benchmark results from v5.10.2

docs/integrate/django/index.md, docs/integrate/framework.md
Educate users about [cratedb-django](https://github.com/crate/cratedb-django). Thanks, @surister! ✨ 
https://cratedb-guide--225.org.readthedocs.build/integrate/django/
=> Integrate: Add page about Django

docs/connect/drivers.md, docs/home/index.md
This patch is implementing a suggestion to add a preamble to the "Home" page of the CrateDB Guide. It includes two sections "Why CrateDB?" and "What Can You Build?".
**Source:** https://cratedb.gitbook.io/cratedb-docs/K3l1K4ZBSqj0AL16dbZi
**Preview:** https://cratedb-guide--234.org.readthedocs.build/home/
- GH-227
=> Home: Add "Welcome to CrateDB" teaser text

docs/index.md, docs/ingest/index.md, docs/integrate/index.md, docs/integrate/telemetry/index.md
Making a start on recent requests about having a page that bundles all data ingestion methods on a single spot.
**Source:** https://cratedb.gitbook.io/cratedb-docs/K3l1K4ZBSqj0AL16dbZi/getting-started/ingesting-data
**Source:** https://cratedb.gitbook.io/cratedb-docs/K3l1K4ZBSqj0AL16dbZi/drivers-and-integrations/data-sources
**Preview:** https://cratedb-guide--230.org.readthedocs.build/ingest/
Future patches will provide curations to recommend canonical ingest methods, preferably of polyglot nature, possibly tailored/native to CrateDB.
- GH-224
=> Ingest: Add page about ingestion methods

docs/_include/links.md, docs/_include/styles.html, docs/connect/drivers.md, docs/connect/index.md, docs/ingest/cdc/index.md, docs/ingest/etl/index.md, docs/ingest/index.md, docs/ingest/telemetry/index.md, docs/integrate/apache-airflow/index.md, docs/integrate/apache-iceberg/index.md, docs/integrate/aws-lambda/index.md, docs/integrate/azure-functions/index.md, docs/integrate/azure-functions/learn.rst, docs/integrate/index.md, docs/integrate/marquez/index.md, docs/integrate/n8n/index.md
Following up on the previous layout patch GH-238, this one adds more guidance to the ETL and CDC category pages, in form of reasonable groupings that try to strike the balance, using [card design elements] to contain related elements.
[card design elements]: https://m3.material.io/components/cards/overview
> To this end, the new “Ingest” section now has absolutely NO “walls of links” any longer on its category pages `etl` and `cdc`, but instead offers **better guidance** in the form of _labeled cards_.
Along the lines, also add missing integration items about `aws-lambda` and `n8n`.
- https://cratedb-guide--239.org.readthedocs.build/ingest/etl/
- https://cratedb-guide--239.org.readthedocs.build/ingest/cdc/
- GH-227
- GH-238
=> ETL/CDC: Guidance, Layout / Dissolve walls of links

docs/ingest/etl/index.md, docs/integrate/index.md, docs/integrate/mongodb/tutorial.md, docs/integrate/mqtt/index.md, docs/integrate/mqtt/tutorial.md
Using Eclipse Mosquitto and LorryStream to invoke a data transfer procedure from an MQTT topic into a CrateDB table, all based on using Docker for executing any command.
- https://cratedb-guide--247.org.readthedocs.build/integrate/mqtt/
- https://cratedb-guide--247.org.readthedocs.build/integrate/mqtt/learn.html
- https://cratedb-guide--247.org.readthedocs.build/ingest/etl/
- GH-227
- GH-242
/cc @karynzv, @hammerhead, @surister
=> Integrate/MQTT: Add entry point page, micro tutorial, and category item

docs/integrate/index.md, docs/integrate/mindsdb/index.md, docs/topic/ml/index.md
_Re-submitting this here from https://github.com/crate/crate-clients-tools/pull/118 by @chandrevdw31 -- thanks!_
> Added MindsDB to docs. MindsDB integrates with CrateDB, making data from CrateDB accessible to a diverse range of AI/ML models. Feel free to ask any questions.
https://cratedb-guide--253.org.readthedocs.build/integrate/mindsdb/
=> Integrate: Add MindsDB

docs/integrate/influxdb/cloud.md, docs/integrate/influxdb/index.md, docs/integrate/influxdb/model.md, docs/integrate/influxdb/tutorial.md
The goal is to present concise walkthroughs without many bells and whistles, which get to the point of getting you started quickly.
The content now uses the established template for the starter tutorial in `tutorial.md`. What's different here is that the backbone section also includes two separate files now, one educating about InfluxDB's data model, and the other one specifically educating about usage in Cloud environments.
https://cratedb-guide--255.org.readthedocs.build/integrate/influxdb/tutorial.html
=> Integrate/InfluxDB: Simplify starter tutorial

docs/conf.py, docs/integrate/mongodb/cloud.md, docs/integrate/mongodb/index.md, docs/integrate/mongodb/model.md, docs/integrate/mongodb/tutorial.md
The goal is to present concise walkthroughs without many bells and whistles, which get to the point of getting you started quickly.
The content now uses the established template for the starter tutorial in `tutorial.md`. What's different here is that the backbone section also includes two separate files now, one educating about MongoDB's data model, and the other one specifically educating about usage in Cloud environments.
https://cratedb-guide--254.org.readthedocs.build/integrate/mongodb/tutorial.html
https://cratedb-guide--254.org.readthedocs.build/integrate/mongodb/
=> Integrate/MongoDB: Simplify starter tutorial

docs/admin/troubleshooting/cfr.md
Currently, binary download artefacts for CFR are produced by the GHA workflow "[Release: Application Bundle](https://github.com/crate/cratedb-toolkit/actions/workflows/release-app.yml)". They have a TTL of 3 months or so, so this patch refreshes the download links.
- https://github.com/crate/cratedb-toolkit/issues/160
=> CFR: Update links for download artefacts

docs/integrate/kafka/attic.md, docs/integrate/kafka/docker-python.md, docs/integrate/kafka/index.md, docs/integrate/kafka/kafka-connect.md
Pulling new content about integrating with Apache Kafka. Thanks, @zolbatar!
**Source:** https://cratedb.gitbook.io/cratedb-docs/K3l1K4ZBSqj0AL16dbZi/drivers-and-integrations/data-sources/streaming-platforms/kafka-daryl
**Preview:** https://cratedb-guide--263.org.readthedocs.build/integrate/kafka/
**Preview:** https://cratedb-guide--263.org.readthedocs.build/integrate/kafka/docker-python.html
- GH-227
=> Integrate/Kafka: Rework section. Add Python tutorial.

docs/integrate/telegraf/index.md, docs/integrate/telegraf/tutorial.md
Using Telegraf and CrateDB to collect and store system metrics, all based on using Docker for executing any command.
- https://cratedb-guide--267.org.readthedocs.build/integrate/telegraf/
- https://cratedb-guide--267.org.readthedocs.build/integrate/telegraf/tutorial.html
- https://cratedb-guide--267.org.readthedocs.build/ingest/telemetry/
- GH-227
- GH-243
- GH-247 (similar)
/cc @hammerhead
=> Integrate/Telegraf: Add micro tutorial. Improve layout on index page.

docs/integrate/index.md, docs/integrate/r/index.md, docs/integrate/r/tutorial.rst, docs/topic/ml/index.md
Just a bit of refactoring.
- https://cratedb-guide--312.org.readthedocs.build/integrate/r/
- GH-313
=> R: Refactor ML tutorial to dedicated section

docs/integrate/metabase/tutorial.rst
Continue adding tutorials from the community forum.
- https://cratedb-guide--294.org.readthedocs.build/integrate/metabase/
- GH-102
=> Metabase: Carry over podman command from community tutorial

docs/feature/query/index.md, docs/integrate/index.md, docs/integrate/trino/index.md, docs/integrate/trino/tutorial.md
Continue adding tutorials from the community forum.
- https://cratedb-guide--309.org.readthedocs.build/integrate/trino/
- GH-102
=> Trino: Index page and starter tutorial

docs/ingest/telemetry/index.md, docs/integrate/index.md, docs/integrate/rsyslog/index.md, docs/integrate/rsyslog/tutorial.md
Continue adding tutorials from the community forum.
- https://cratedb-guide--305.org.readthedocs.build/integrate/rsyslog/
- https://cratedb-guide--305.org.readthedocs.build/ingest/telemetry/
- GH-102
=> rsyslog: Index page and starter tutorial

docs/integrate/airflow/data-retention-hot-cold.md, docs/integrate/airflow/data-retention-policy.md, docs/integrate/airflow/export-s3.md, docs/integrate/airflow/getting-started.md, docs/integrate/airflow/import-parquet.md, docs/integrate/airflow/import-stock-market-data.md, docs/integrate/airflow/index.md, docs/integrate/arrow/import-parquet.md, docs/integrate/arrow/index.md
- https://cratedb-guide--279.org.readthedocs.build/integrate/airflow/
- https://cratedb-guide--279.org.readthedocs.build/integrate/arrow/
Further improvements can easily happen on subsequent iterations. Let us know what you would like to see fixed/improved immediately, or later, when needed.
- GH-102
=> Airflow: Add tutorials from community forum

docs/integrate/cluvio/index.md, docs/integrate/cluvio/tutorial.md, docs/integrate/cluvio/usage.md, docs/topic/bi/index.md
- https://cratedb-guide--284.org.readthedocs.build/integrate/cluvio/
- GH-102
@coderabbitai: Please review and convert to active voice.
=> Cluvio: Usage guide

docs/integrate/jmeter/index.md
- https://cratedb-guide--290.org.readthedocs.build/integrate/jmeter/
- GH-102
@coderabbitai review and convert to active voice, please.
=> JMeter: Index page with a little "configure" section

docs/integrate/terraform/index.md, docs/integrate/terraform/tutorial.md, docs/integrate/terraform/usage.md
- https://cratedb-guide--308.org.readthedocs.build/integrate/terraform/
- GH-102
=> Terraform: Index page and usage guide

docs/integrate/dbt/index.md, docs/integrate/dbt/usage.md
Just a bit of copy-editing.
https://cratedb-guide--288.org.readthedocs.build/integrate/dbt/
=> dbt: Improve section here and there

docs/conf.py, docs/integrate/debezium/index.md, docs/integrate/debezium/tutorial.md
- https://cratedb-guide--289.org.readthedocs.build/integrate/debezium/
- GH-102
=> Debezium: Tutorial about replicating data from MSSQL

docs/integrate/databricks/azure-databricks.md, docs/integrate/databricks/index.md, docs/integrate/spark/index.md, docs/integrate/spark/tutorial.md, docs/integrate/spark/usage.md
- https://cratedb-guide--281.org.readthedocs.build/integrate/databricks/
- https://cratedb-guide--281.org.readthedocs.build/integrate/spark/
- GH-102
=> Databricks and Spark: Basic usage guides

docs/integrate/superset/index.md, docs/integrate/superset/sandbox.md, docs/integrate/superset/tutorial.md, docs/integrate/superset/usage.md
- https://cratedb-guide--282.org.readthedocs.build/integrate/superset/
- GH-102
=> Superset: Usage guides

docs/connect/df/index.md, docs/integrate/dask/usage.md, docs/integrate/pandas/efficient-ingest.md, docs/integrate/pandas/index.md, docs/integrate/pandas/tutorial-jupyter.md, docs/integrate/pandas/tutorial-start.md
- https://cratedb-guide--297.org.readthedocs.build/integrate/pandas/
- GH-102
=> pandas: Starter and Jupyter tutorial. Guidelines for efficient ingest.

docs/admin/clustering/multi-node-setup.md, docs/admin/clustering/scale/kubernetes.md, docs/conf.py, docs/install/cloud/aws/ec2-setup.rst, docs/install/cloud/azure/vm.rst
We turned off [CrateDB 3.3 docs](https://cratedb.com/docs/crate/reference/en/3.3/) recently.
- https://cratedb-guide--359.org.readthedocs.build/admin/clustering/multi-node-setup.html#seeding-manually
- https://cratedb-guide--359.org.readthedocs.build/admin/clustering/scale/kubernetes.html
- https://cratedb-guide--359.org.readthedocs.build/install/cloud/aws/ec2-setup.html#basic-configuration
- https://cratedb-guide--359.org.readthedocs.build/install/cloud/azure/vm.html#configure-cratedb
=> CrateDB 3.x: Documentation for 3.3 turned off, so refer to sources instead. Also tune down other content.

docs/admin/index.md, docs/start/index.md, docs/start/ingest.md, docs/start/modelling/fulltext.md, docs/start/query/index.md, docs/start/query/search.md
References pointing across the document tree have been reported to display confusing navigation behaviour.
Discovered per `ag "\.\.\/"`.
- https://cratedb-guide--362.org.readthedocs.build/start/ingest.html
- https://cratedb-guide--362.org.readthedocs.build/start/query/search.html
=> Navigation: Dissolve cross-tree references

README.md, docs/integrate/index.md, docs/solution/migrate/rockset/index.md
All the Markdown has been migrated to the CrateDB Guide / Handbook.
-- https://community.cratedb.com/t/overview-of-cratedb-integration-tutorials/1015
- https://github.com/crate/cratedb-guide/issues/102
=> Chore: Remove "Overview of CrateDB integration tutorials"

docs/_include/links.md, docs/feature/document/index.md, docs/feature/document/tutorial.md, docs/feature/document/usage.md, docs/feature/search/fts/index.md, docs/feature/search/fts/tutorial.md, docs/handbook/index.md, docs/howto/index.md, docs/integrate/influxdb/usage.md, docs/integrate/locust/tutorial.md, docs/topic/timeseries/learn/query.md, docs/topic/timeseries/learn/with-metadata.md, docs/tutorial/index.md
After phasing out the [crate-howtos] and [crate-tutorials] repositories, and re-integrating content here, let's use ideas from Diátaxis to loosely start grouping/indexing relevant content again.
Remark: Not many articles enumerated at [Overview of CrateDB integration tutorials] are actually tutorials per [Diátaxis "tutorials" definition], so we slotted most of them into the "how-to" section instead.
- https://cratedb-guide--364.org.readthedocs.build/handbook/#learn
- https://cratedb-guide--364.org.readthedocs.build/howto/
- https://cratedb-guide--364.org.readthedocs.build/tutorial/
- GH-10
- https://github.com/crate/cloud-docs/issues/68
- GH-102
- GH-227
- GH-335
[crate-howtos]: https://github.com/crate/crate-howtos
[crate-tutorials]: https://github.com/crate/crate-tutorials
[Diátaxis …
=> Diátaxis: Index how-to guides and tutorials

docs/_include/links.md, docs/connect/index.md, docs/start/query/ad-hoc.md, docs/start/query/aggregations.md, docs/start/query/ai-integration.md
In pure "learning path" sections, relocate reference links to bottom of page.
- https://cratedb-guide--379.org.readthedocs.build/start/query/aggregations.html
- https://cratedb-guide--379.org.readthedocs.build/start/query/ad-hoc.html
- https://cratedb-guide--379.org.readthedocs.build/start/query/ai-integration.html
- GH-372
=> Navigation: Relocate reference links in learning path sections
