crate/cratedb-guide

- docs/index.rst
Removed "machine" from "machine data" based on Stephane's request
> Adjust "machine data" mention

- docs/admin/performance/memory.rst
- Refactoring the page about CrateDB's _Memory Configuration_.
- Carried over from https://github.com/crate/crate-howtos/pull/316.
https://cratedb-guide--17.org.readthedocs.build/admin/performance/memory.html
> Improve section about memory recommendations

- docs/requirements.txt
Includes most recent updates to the crate-docs-theme. Most prominently, an update to the weight of the h1 headers.
- https://github.com/crate/crate-docs-theme/pull/466
> Dependencies: Update to crate-docs-theme==0.30.0.dev6

- docs/admin/performance/selects.rst
Introduce and cross-link to community articles by @hlcianfagna. Thanks a stack!
Please advise if you think it makes sense to present the corresponding content like outlined in this PR, and if you see there should be made any improvements to their "short-hand" variants. Please advise differently if you think it is nonsense, or should be made totally different.
- [Performance: Add section "Replace JOINs with CTEs"](https://github.com/crate/cratedb-guide/commit/41b69dd6fcee738a21cd3f16133063973cddf0a9)
- [Performance: Add section about "retrieving records in bulk"](https://github.com/crate/cratedb-guide/commit/b78570b5d1db1f6d018819d2539b34ec32f585a3)
- https://cratedb-guide--41.org.readthedocs.build/admin/performance/selects.html#rewrite-joins-as-ctes
- …
> Performance: Reference articles about performance tricks for SQL SELECT queries

- docs/_include/styles.html
- docs/domain/analytics/index.md
- docs/domain/index.md
- docs/domain/industrial/index.md
- docs/domain/timeseries/index.md
- docs/feature/index.md
- docs/index.md
On a few "index" pages where there have been walls of links before, improve the guidance by providing insights about "what's inside" the relevant content sections.
https://cratedb-guide--58.org.readthedocs.build/domain/
> Guidance: Improve "Features" and "Application Domains" pages

- docs/requirements.txt
What the title says.
For testing some upstream changes to the documentation theme submitted by @msbt. Thanks!
- https://github.com/crate/crate-docs-theme/pull/470
- https://github.com/crate/crate-docs-theme/pull/471
https://cratedb-guide--59.org.readthedocs.build/
> Update to crate-docs-theme==0.30.0.dev8

- docs/domain/ml/index.md
GH-66 experienced build errors. This patch intends to take care about fixing a broken link.
> ML: Fix broken links to fundamental LangChain tutorials

- docs/install/windows.rst
Removed "yet", as this indicates we will add production support soon while it is unclear when and if at all we will do this.
> Adjust windows installation production notes

- docs/integrate/etl/influxdb.md
Fix for a small issue introduced by https://github.com/crate/cratedb-guide/pull/75
> Fix formatting issue in tutorial

- docs/integrate/etl/influxdb.md
Found here: https://github.com/crate/cratedb-guide/issues/79
> Fix typo in InfluxDB migration tutorial

- docs/integrate/etl/influxdb.md
The improvements inside aim to address GH-82, and also add a few more other conveniences.
https://cratedb-guide--85.org.readthedocs.build/integrate/etl/influxdb.html
> ETL: Fix and improve tutorial about import from InfluxDB

- docs/requirements.txt
@msbt submitted a few more fixes. This patch intends to snap them live, to have a closer look.
- https://github.com/crate/crate-docs-theme/pull/510
https://cratedb-guide--109.org.readthedocs.build/
/cc @surister, @simonprickett, @kneth
> Update to crate-docs-theme==0.34.0.dev4, for evaluation purposes

- docs/install/tarball.rst
Second PR looking at https://github.com/crate/tech-writing/issues/426
- Adds a note suggesting to manually build CrateDB on ARM-based systems for improved performance
- Language edit in one other note
https://cratedb-guide--114.org.readthedocs.build/install/tarball.html#install-macos
> Install: Address performance issues on ARM-based systems

- docs/requirements.txt
No need to nail dependencies any longer.
> Dependencies: crate-docs-theme==0.34.0 has been released

- docs/home/index.md
Slightly shorten the texts and avoid repetitions.
> Home: Slightly shorten and adjust intro texts

- docs/domain/industrial/index.md
- docs/feature/index/index.md
- docs/integrate/etl/mongodb.md
- docs/requirements.txt
This compensates for changes introduced by Read The Docs, for previewing purposes before rolling it out to other projects.
https://about.readthedocs.com/blog/2024/07/addons-by-default/
- https://github.com/crate/crate-docs-theme/pull/535
> Chore: Update to crate-docs-theme 0.35.0

- docs/requirements.txt
> Chore: Update to crate-docs-theme 0.35.0 GA

- docs/migrate/rockset/query.md
This add equivalences for the position and split scalar functions
> Add position and split to list of functions equivalence 

- docs/home/index.md
Simplifying starting points to Cloud, DB manual, and driver pointers. Adding exploit list with CrateDB features aligned with overall marketing.
https://cratedb-guide--139.org.readthedocs.build/home/
> Home: Update the landing page to align with the marketing messaging

- docs/home/index.md
Just a little cosmetic update to improve the reading flow.
https://cratedb-guide--143.org.readthedocs.build/home/
> Home: Break down wall of text in "CrateDB Cloud" card

- docs/performance/index.rst
- docs/performance/storage.md
- docs/performance/storage_usage.md
- docs/performance/storage_usage.rst
The idea is to explain how different CrateDB options affect disk usage, and techniques to reduce disk usage.
https://cratedb-guide--154.org.readthedocs.build/performance/storage.html
Addresses things like:
- https://community.cratedb.com/t/disk-space-issues-on-prometheus-integration/1848/7
- https://community.cratedb.com/t/disk-space-allocation-concerns-with-longhorn/1915
Potentially add things from:
- https://community.cratedb.com/t/optimizing-storage-for-historic-time-series-data/762/10
> Guide on disk storage size

- docs/migrate/rockset/query.md
This adds a new entry for ARRAY_INTERSECT to the Rockset migration page.
> Add translation for Rockset's ARRAY_INTERSECT

- docs/conf.py
- docs/install/container/docker.rst
- docs/integrate/etl/streamsets.rst
> Chore: Fix link checker on broken links

- docs/feature/index/index.md
- docs/migrate/rockset/index.md
- docs/migrate/rockset/query.md
https://rockset.com/ has been dissolved.
> Chore: Fix broken links to rockset.com, as it went offline

- docs/feature/search/fts/index.md
Compensate chilling effects.
- GH-186
> Chore: Fix broken links to trec.nist.gov

- docs/getting-started.md
- docs/integrate/etl/streamsets.rst
The link checker reported a few links lost connectivity, so this signal appeared on our daily check list.
> Chore: Fix broken links. streamsets.com -> ibm.com

- docs/requirements.txt
Probing some fixes and improvements.
https://cratedb-guide--194.org.readthedocs.build/
- https://github.com/crate/crate-docs-theme/pull/594
- https://github.com/crate/crate-docs-theme/pull/596
- https://github.com/crate/crate-clients-tools/pull/246
> Dependencies: Update to crate-docs-theme 0.38.4

- docs/performance/designing_for_scale.rst
- docs/performance/index.rst
- docs/performance/optimization.rst
This new PR is to replace the other PR on the same topic. Let's ship this.
Preview:
- https://cratedb-guide--196.org.readthedocs.build/performance/optimization.html
- https://cratedb-guide--196.org.readthedocs.build/performance/designing_for_scale.html
> Optimization and productizing docs

- docs/integrate/bi/powerbi-gateway.rst
- docs/performance/selects.rst
> Maintenance: Fix broken links

- docs/admin/sharding-partitioning.rst
- docs/integrate/visualize/r.rst
- docs/performance/scaling.rst
"make check" generated 2 warnings and one error. So I reworded and had to suppress one warning.
> Fix proselint errors/warnings

- docs/admin/circuit-breaker.rst
- docs/admin/index.rst
The goal is to add a page that has a complete guide on CB and most importantly the CB exception info, to provide users with the context on why that happens and what they should do about it.
Please, feel free to edit it and provide feedback so we can improve this and make it as accurate as possible.
> Dedicated `CircuitBreaker` page

- docs/performance/storage.md
Removal of (missed) in page TOC.
Fixes #140
> Remove inpage TOC

- docs/admin/clustering/multi-zone-setup.md
- docs/admin/going-into-production.md
- docs/admin/upgrade/full.md
- docs/admin/upgrade/planning.md
- docs/feature/ccr/index.md
- docs/install/_post-install.rst
What the title says.
@coderabbitai ignore
> Chore: Fix broken Sphinx references

- docs/feature/query/index.md
- docs/performance/inserts/methods.md
- docs/performance/inserts/parallel.md
- docs/performance/inserts/tuning.md
- docs/performance/scaling.md
What the title says.
- GH-323
@coderabbitai ignore
> Chore: Fix more broken Sphinx references

- docs/integrate/balena/index.md
- docs/integrate/balena/tutorial.md
- docs/integrate/balena/usage.md
- https://cratedb-guide--283.org.readthedocs.build/integrate/balena/
- GH-102
@coderabbitai: Please review and convert to active voice.
/cc @karynzv, @kneth, @surister, @mpous
> Balena: Index page and usage guide

- docs/integrate/dapr/index.md
- docs/integrate/dapr/tutorial.md
- docs/integrate/dapr/usage.md
- https://cratedb-guide--285.org.readthedocs.build/integrate/dapr/
- GH-102
> Dapr: Index page and usage guide

- docs/feature/query/index.md
- docs/feature/query/recurrent.md
- docs/integrate/node-red/index.md
- https://cratedb-guide--296.org.readthedocs.build/feature/query/recurrent.html
- GH-102
> Advanced querying: Automating recurrent CrateDB queries
